version: "3.8"
services:
  mongo_db:
    image: "mongo:4.4.3"
    container_name: mongo-database
    restart: always
    ports:
      - 27017:27017
    networks:
      - database
networks:
  database:
    driver: bridge
volumes:
  database: